#!/bin/bash

#make Project folder
Project=NameofProject
mkdir /home/centos/$Project

#get Scripts from github folder
wget https://github.com/Ibexguy/aDNA_Ibex/archive/b674ebbc9f013496db8741e298ac065c20e6e9c6.zip /home/centos/$Project
unzip /home/centos/$Project/b674ebbc9f013496db8741e298ac065c20e6e9c6.zip /home/centos/$Project
rm /home/centos/$Project/b674ebbc9f013496db8741e298ac065c20e6e9c6.zip

#make all skripts executable
cd /home/centos/$Project
find -maxdepth 1 -type f -name "*.sh" -exec chmod +x \{\} \;
